# Generated by Django 6.0.4 on 2026-06-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0003_chat_message'),
        ('users', '0009_propriedade_comodidades_propriedade_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.propriedade'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.propriedade'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_tenancies', to='users.propriedade'),
        ),
    ]
