# Generated by Django 6.0.4 on 2026-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0004_alter_application_property_alter_chat_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='payment_status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
