# Generated by Django 6.0.4 on 2026-06-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_landlord_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Inquilino'), ('landlord', 'Senhorio'), ('admin', 'Administrador')], default='inquilino', max_length=20),
        ),
    ]
