# Generated by Django 6.0.4 on 2026-06-11 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_landlord_approved_user_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('inquilino', 'Inquilino'), ('senhorio', 'Senhorio'), ('admin', 'Administrador')], default='inquilino', max_length=20),
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morada', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Vazio (Pronto a anunciar)', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('senhorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
