# Generated by Django 6.0.4 on 2026-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_propriedade'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='propriedades/'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='tipo_casa',
            field=models.CharField(choices=[('apartamento', 'Apartamento'), ('moradia', 'Moradia'), ('quarto', 'Quarto')], default='apartamento', max_length=20),
        ),
    ]
