# Generated by Django 6.0.4 on 2026-06-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_propriedade_foto_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='anuncio_publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='preco_anuncio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='titulo_anuncio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
