# Generated by Django 6.0.4 on 2026-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_propriedade_anuncio_publicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Inquilino'), ('landlord', 'Senhorio'), ('admin', 'Administrador')], default='inquilino', max_length=20),
        ),
    ]
