# Generated by Django 6.0.5 on 2026-06-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_propriedade_anuncio_publicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='morada_fiscal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Inquilino'), ('landlord', 'Senhorio'), ('admin', 'Administrador')], default='tenant', max_length=20),
        ),
    ]
