# Generated by Django 6.0.4 on 2026-06-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
        ('users', '0007_user_telefone'),
    ]

    operations = [
    ]
