# Generated by Django 6.0.4 on 2026-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0006_alter_user_role_0007_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='comodidades',
            field=models.CharField(blank=True, default='Cozinha Equipada, Excelente Exposição Solar, Zona Tranquila', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='descricao',
            field=models.TextField(blank=True, default='Fantástico imóvel com excelentes áreas e muita luz natural. Localizado numa zona tranquila e com ótimos acessos.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Inquilino'), ('landlord', 'Senhorio'), ('admin', 'Administrador')], default='tenant', max_length=20),
        ),
    ]
