# Generated by Django 6.0.4 on 2026-06-12 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_propriedade_comodidades_propriedade_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSubscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('max_propriedades', models.IntegerField(default=1)),
                ('max_anuncios', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.planosubscricao'),
        ),
    ]
