# Generated by Django 6.0.4 on 2026-06-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_planosubscricao_user_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosubscricao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
