# Generated by Django 6.0.4 on 2026-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documento_verificacao',
            field=models.FileField(blank=True, null=True, upload_to='verificacao_senhorios/'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_verificacao',
            field=models.CharField(choices=[('pendente', 'Pendente de Verificação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
    ]
